### ISSUE TITLE
Using project config with craft-shortcodes errors on Schema version

### ISSUE THREAD

**Issue by FreekVR** [samhernandez/craft-shortcodes#4]
I have a project which I have migrated from Craft 2 to Craft 3 and now have project config enabled and craft-shortcodes installed.

However, now upon visiting the admin UI the following error is shown:
```
Shortcodes currently installed has the schema version of 0.0.1 (expected 1.0.0)
```
Upon further inspection, it looks like in the Shortcodes plugin class, a schema version is defined as `public $schemaVersion = '0.0.1';`, but in the `plugins` table, it has a schemaVersion defined as `1.0.0`.

It seems like the default schema version for plugins without any migrations is now `1.0.0` in Craft 3. I've found this defined in the craft `PluginTrait` and in a migration called `m161006_205918_schemaVersion_not_null` as the fallback version.

Thus, I would suggest changing the defined schema version in the `Shortcodes` class to 1.0.0 as that seems to mitigate the issue.

**Comment by samhernandez** [comment]
@FreekVR thank you! Updated in this commit and I'll tag a new release right quick. https://github.com/samhernandez/craft-shortcodes/commit/a0502a8ce3328b7feb26b4186363006e392ac4e3

**Comment by FreekVR** [comment]
Thanks for the quick fix. Looks like it's been tagged over here but it's not yet showing 1.0.3 on packagist (https://packagist.org/packages/samhernandez/craft-shortcodes) Any chance you could update it there as well?

**Comment by samhernandez** [comment]
Apologies for the delay. A new release shows up on Packagist now
