### ISSUE TITLE
PHP Error: Passing the encoding as third parameter is deprecated

### ISSUE THREAD

**Issue by Skartz** [samhernandez/craft-shortcodes#7]
The following error appears on entries with shortcodes in use
`mb_strrpos(): Passing the encoding as third parameter is deprecated. Use an explicit zero offset`

Found updating Line 139 in `/vendor/thunderer/shortcode/src/Processor/Processor.php` to have an explicit zero offset has resolved the error for me. I have not done additional testing to see if anything else has been impacted by this change at this time.

### Additional info

- Craft version: 3.4.22.1
- PHP version: 7.4.6
- Plugins & versions: 1.0.4

**Comment by sparkalow** [comment]
Any plans to merge this into an official release? This is needed to support php 7.4.

**Comment by samhernandez** [comment]
Merged! apologies for the delay
