### ISSUE TITLE
Update for Craft 4

### ISSUE THREAD

**Issue by samhernandez** [samhernandez/craft-shortcodes#9]
Needs an update and release for Craft 4

**Comment by patrikalienus** [comment]
Will there come an update for Craft 4 compatibility?

**Comment by simonkuran** [comment]
Any news on this plugin getting a Craft 4 update? This is the one plugin holding me back from updating a site.

**Comment by engram-design** [comment]
Just to chime in @samhernandez, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3), as people are keen to see this plugin on Craft 4.

If you're no longer developing this plugin, we'd be happy to continue development at Verbb (including updating to Craft 4). If that's the case, you'd be welcome to transfer this repository to `verbb` or myself `engram-design` (you might have to add me as a collaborator first, then promote to admin). But only if you're looking to part ways with the plugin of course!

**Comment by MoritzLost** [comment]
For anyone looking for a quick solution: The plugin is very simple and can easily be moved to a site-specific module. I ended up doing that for a site I updated to Craft 4. If you take out the configuration options (you can specify those in the module anyway), all you need is to install the [shortcode library](https://github.com/thunderer/Shortcode) via Composer and add some boilerplate code to initialize it and add the `shortcodes` filter.

Here's the module file that registers a Twig extension that provides the shortcode filter:

```php
// modules/Shortcodes/ShortcodesModule.php

<?php

namespace modules\Shortcodes;

use Craft;
use modules\Shortcodes\Extension\Shortcodes;

class ShortcodesModule extends \yii\base\Module
{
    public function init()
    {
        Craft::$app->view->registerTwigExtension(new Shortcodes);

        parent::init();
    }
}
```

And here's the corresponding Twig extension:

```php
// module/Shortcodes/Extension/Shortcodes.php

<?php

namespace modules\Shortcodes\Extension;

use Craft;
use craft\helpers\Template;
use craft\web\View;
use Thunder\Shortcode\Shortcode\ShortcodeInterface;
use Thunder\Shortcode\ShortcodeFacade;
use Twig\Extension\AbstractExtension;
use Twig\Markup;
use Twig\TwigFilter;

class Shortcodes extends AbstractExtension
{
    private ?ShortcodeFacade $facade = null;

    public function getFilters()
    {
        return [
            new TwigFilter('shortcodes', $this->shortcodesFilter(...)),
        ];
    }

    public function shortcodesFilter(?string $value): null|string|Markup
    {
        if (!$value) return $value;

        $facade = $this->createShortcodeFacade();
        return Template::raw($facade->process($value));
    }

    private function createShortcodeFacade(): ShortcodeFacade
    {
        if (!$this->facade) {
            $this->facade = new ShortcodeFacade();

            $shortcodes = Craft::$app->getConfig()->custom->shortcodes;
            foreach ($shortcodes as $name => $template) {
                $this->facade->addHandler(
                    $name,
                    fn (ShortcodeInterface $s) => $this->renderShortcodeTemplate($template, $s),
                );
            }
        }
        return $this->facade;
    }

    private function renderShortcodeTemplate(string $template, ShortcodeInterface $shortcode): string
    {
        /** @var craft\web\View $view */
        $view = Craft::$app->getView();
        return $view->renderTemplate(
            $template,
            ['shortcode' => $shortcode],
            View::TEMPLATE_MODE_SITE,
        );
    }
}
```

Finally, move the shortcodes configuration out of `config/shortcodes.php` to `config/custom.php`:

```php
// config/custom.php

<?php

return [
    'shortcodes' => [
        'myawesomeshortcode' => 'shortcodes/my-awesome-shortcode',
    ]
];
```

If you need to adjust any options (like using a regular parser), you can do that through the ShortcodeFacade.

**Comment by samhernandez** [comment]
@engram-design thank you! I don't have time to maintain it (obviously) so it's all yours!

**Comment by engram-design** [comment]
Thanks @samhernandez we'll get onto it!

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/shortcodes/releases/tag/3.0.0)
